apiVersion: batch/v1
kind: Job
metadata:
  name: pre-uninstall-component-check
  annotations:
    "helm.sh/hook" : pre-delete
    "helm.sh/weight" : "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      serviceAccountName: odacomponent-account
      containers:
        - name: component-checker
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Checking for component Custom Resources (CRs) in the canvas cluster..."
              if kubectl get <your-component-crd> -A | grep -q "<component-name>"; then
                echo "Error: Component CRs are present in the cluster. Uninstallation aborted."
                exit 1  #Exits to prevent Helm from proceeding
              else
                echo "No component CRs found. Proceeding with uninstallation."
              fi
      restartPolicy: Never
  backoffLimit: 1
