apiVersion: v1
kind: Pod
metadata:
  name: pre-delete-component-check
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  restartPolicy: Never
  containers:
    - name: check-components
      image: bitnami/kubectl:latest
      command:
        - /bin/sh
        - -c
        - |
          echo "Checking for component Custom Resources (CRs) in the cluster..."
          COMPONENT_COUNT=$(kubectl get components.oda.tmforum.org -A --no-headers | wc -l)
          if [ "$COMPONENT_COUNT" -gt 0 ]; then
            echo "Error: Uninstallation aborted as components are present in the cluster."
            kubectl get components.oda.tmforum.org -A
            exit 1  # Exit to prevent Helm from proceeding
          else
            echo "No component CRs found. Proceeding with uninstallation."
          fi
