apiVersion: v2
name: canvas-api-gateway
description: A Helm of helm to orchestrate the ODA API Gateway installation

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.9
# version: 1.1.5-rc1
# version: 1.1.5-r1 - ODAA-86: downgrade HashiCorp Vault to 1.14.8. Last version under MPLv2, 
#                  see https://www.hashicorp.com/license-faq#products-covered-by-bsl
# version: 1.1.4 - added secretsmanagement-operator
# version: 1.1.3 - updated dependentApiSimpleOperator to tmforum docker repo
# version: 1.1.2 - added dependentApiSimpleOperator
# version: 1.1.1 - bug fix for empty specification property of exposedAPI
# version: 1.1.0 - updated component CRD to support an array for the specification field in the exposed API (to support Gen5 APIs)
# version: 1.0.0 - baseline version

# This is the version number of the application being deployed. We are versioning the canvas as the
# version of the latest component spec that it supports.
appVersion: "v1beta3"

dependencies:
  - name: kong-gateway
    version: "0.1.0"
    repository: 'file://../canvas-api-gateway/kong-gateway'
    condition: kong-gateway-install.enabled
  - name: apisix-gateway
    version: "0.1.0"
    repository: 'file://../canvas-api-gateway/apisix-gateway'
    condition: apisix-gateway-install.enabled




