# values.yaml for canvas-api-gateway

# Configuration for kong-gateway installation
kong-gateway-install:
  enabled: false  # Enable kong-gateway if needed
  kong:
    # Direct configurations to the kong sub-chart if needed
    deployment:
      enabled: true
      serviceAccount:
        create: true
        automountServiceAccountToken: false
      test:
        enabled: false
    env:
      database: "postgres"
      pg_host: "kong-postgresql.kong.svc.cluster.local"
      pg_user: "kong"
      pg_password: "kong"
      pg_database: "kong"
      router_flavor: "traditional"
      nginx_worker_processes: "2"
      proxy_access_log: "/dev/stdout"
      admin_access_log: "/dev/stdout"
      admin_gui_access_log: "/dev/stdout"
      portal_api_access_log: "/dev/stdout"
      proxy_error_log: "/dev/stderr"
      admin_error_log: "/dev/stderr"
      admin_gui_error_log: "/dev/stderr"
      portal_api_error_log: "/dev/stderr"
      prefix: "/kong_prefix/"
    admin:
      enabled: true
      type: NodePort
    proxy:
      enabled: true
      type: LoadBalancer

# Configuration for apisix-gateway installation
apisix-gateway-install:
  enabled: false  # Enable apisix-gateway if needed
  apisix:
    gateway:
      type: LoadBalancer
    ingress-controller:
      config:
        apisix:
          adminAPIVersion: v3
      serviceNamespace: ingress-apisix
      enabled: true
