apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-operator
  namespace: ingress-apisix
spec:
  replicas: {{ .Values.apisixoperatorreplicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-operator
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-operator
    spec:
      serviceAccountName: {{ .Release.Name }}-operator
      initContainers:
        - name: wait-apisix-admin
          image: {{ .Values.initContainer.image }}:{{ .Values.initContainer.tag }}
          command:
            - sh
            - -c
            - |
              {{ if .Values.config.apisix.serviceFullname }}
              until nc -z {{ .Values.config.apisix.serviceFullname }} {{ .Values.config.apisix.servicePort }}; do echo waiting for apisix-admin; sleep 2; done;
              {{ else }}
              until nc -z {{ .Values.config.apisix.serviceName }}.{{ .Values.config.apisix.serviceNamespace }}.svc.{{ .Values.clusterDomain }} {{ .Values.config.apisix.servicePort }}; do echo waiting for apisix-admin; sleep 2; done;
              {{ end }}
      containers:
      - name: {{ .Release.Name }}-operator
        image: {{ .Values.apisixoperatorimage.repository }}
        imagePullPolicy: {{ .Values.apisixoperatorimage.pullPolicy }}
