apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix-operator
  namespace: ingress-apisix
spec:
  replicas: {{ .Values.operatorreplicaCount }}
  selector:
    matchLabels:
      app: apisix-operator
  template:
    metadata:
      labels:
        app: apisix-operator
    spec:
      serviceAccountName: apisix-operator
      containers:
      - name: apisix-operator
        image: {{ .Values.operatorimage.repository }}
        imagePullPolicy: {{ .Values.operatorimage.pullPolicy }}
