{{- if eq (len (lookup "v1" "Namespace" "" .Values.kongnamespace)) 0 }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.kongnamespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
    #"helm.sh/hook": pre-install,pre-upgrade
    #"helm.sh/hook-weight": "-5"
{{- end }}
