apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-operator-job
  namespace: kong
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-operator
      initContainers:
        - name: wait-kong-admin
          image: busybox:1.28
          command:
            - sh
            - -c
            - |
              until nc -z kong-kong-admin.kong.svc.cluster.local 8001; do echo waiting for kong-admin; sleep 2; done;
      containers:
      - name: {{ .Release.Name }}-operator
        image: {{ .Values.kongoperatorimage.repository }}
        imagePullPolicy: {{ .Values.kongoperatorimage.pullPolicy }}
      restartPolicy: Never
  backoffLimit: 3
