apiVersion: batch/v1
kind: Job
metadata:
  name: install-gateway-api
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: kubectl-apply
        image: bitnami/kubectl:latest
        command: ["kubectl", "apply", "-f", "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml"]
      restartPolicy: OnFailure
