apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-wait-kong-admin
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-wait-kong-admin
    spec:
      containers:
      - name: wait-kong-admin
        image: busybox:1.28
        command:
          - sh
          - -c
          - |
            until nc -z kong-kong-admin.kong.svc.cluster.local 8001; do echo "waiting for kong-admin"; sleep 2; done;
      restartPolicy: Never
  backoffLimit: 3
