apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-command
  namespace: canvas
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"  # Ensures it runs after the init Job completes
data:
  run-command: |
    apiOperatorKong
