apiVersion: v1
kind: ConfigMap
metadata:
  name: reference-grant-config
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
data:
  referenceGrant.yaml: |
    apiVersion: gateway.networking.k8s.io/v1beta1
    kind: ReferenceGrant
    metadata:
      name: allow-http-route-access
      namespace: istio-ingress
    spec:
      from:
        - group: gateway.networking.k8s.io
          kind: HTTPRoute
          namespace: components
      to:
        - group: ""
          kind: Service
          name: istio-ingress
