gateway:
  type: LoadBalancer  # Override the service type

ingress-controller:
  config:
    apisix:
      adminAPIVersion: v3
  serviceNamespace: ingress-apisix
  enabled: true   # Explicitly enable the ingress controller

apisixoperatorreplicaCount: 1
apisixistiooperatordeploymentnamespace: canvas
apisixoperatorimage:
  repository: ravijangra92/apisix-operator:7.9.0
  pullPolicy: IfNotPresent
