apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-command
  labels:
    {{- include "controller.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1" 
data:
  run-command: |
    kopf run --namespace=$COMPONENT_NAMESPACE componentOperator/componentOperator.py apiOperatorIstio/apiOperatorIstio.py securityController/securityControllerKeycloak.py
