name: API Gateway Release Workflow

on:
  push:
    branches:
      - feature-update-istio-apigateway-2

concurrency:
  group: chart-release
  cancel-in-progress: false
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Configure Helm
        run: |
          cd ./charts/canvas-api-gateway/combined-api-gateway-chart
          helm dependency update
          cd apisix-gateway
          helm dependency update
          cd ../kong-gateway
          helm dependency update
          cd ../
          ls -la
          helm dependency update


      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: ./charts/canvas-api-gateway
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
