name: API Gateway and Helm Chart Release Workflow

on:
  push:
    branches:
      - feature-update-istio-apigateway-2

concurrency:
  group: chart-release
  cancel-in-progress: false

jobs:
  release-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Configure Helm for general charts
        run: |
          # Add required Helm repositories
          helm repo add jetstack https://charts.jetstack.io
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add hashicorp https://helm.releases.hashicorp.com
          helm repo update
          
          # Update dependencies for cert-manager-init chart
          cd ./charts/cert-manager-init
          helm dependency update

          # Update dependencies for canvas-vault chart
          cd ../canvas-vault
          helm dependency update

          # Update dependencies for canvas-oda chart
          cd ../canvas-oda
          helm dependency update

      - name: Run chart-releaser for Helm Charts
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: ./charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Sleep for 60 seconds
        run: sleep 60

  delay-for-canvas-chart-release:
    runs-on: ubuntu-latest
    needs: release-charts
    steps:
      - name: Confirm new release was done properly
        run: |
          # Add the required Helm repository
          helm repo add oda-canvas-api-gateway https://rj-acc.github.io/oda-canvas-api-gateway
          helm repo update

          # Check for the latest version of the cert-manager-init chart
          latest_cert_manager=$(helm search repo oda-canvas-api-gateway/cert-manager-init --versions | awk 'NR==2 {print $2}')
          if [ -z "$latest_cert_manager" ]; then
            echo "Error: cert-manager-init chart release was not successful."
            exit 1
          else
            echo "cert-manager-init chart released successfully. Version: $latest_cert_manager"
          fi

          # Check for the latest version of the canvas-vault chart
          latest_canvas_vault=$(helm search repo oda-canvas-api-gateway/canvas-vault --versions | awk 'NR==2 {print $2}')
          if [ -z "$latest_canvas_vault" ]; then
            echo "Error: canvas-vault chart release was not successful."
            exit 1
          else
            echo "canvas-vault chart released successfully. Version: $latest_canvas_vault"
          fi

          # Check for the latest version of the canvas-oda chart
          latest_canvas_oda=$(helm search repo oda-canvas-api-gateway/canvas-oda --versions | awk 'NR==2 {print $2}')
          if [ -z "$latest_canvas_oda" ]; then
            echo "Error: canvas-oda chart release was not successful."
            exit 1
          else
            echo "canvas-oda chart released successfully. Version: $latest_canvas_oda"
          fi

          echo "All charts released successfully."

      - name: Sleep for 60 seconds
        run: sleep 60

  release-api-gateway:
    runs-on: ubuntu-latest
    needs: delay-for-canvas-chart-release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Configure Helm for API Gateway
        run: |
          cd ./charts/canvas-api-gateway/combined-api-gateway-chart
          helm dependency update

          # Update dependencies for apisix-gateway chart
          cd apisix-gateway
          helm dependency update

          # Update dependencies for kong-gateway chart
          cd ../kong-gateway
          helm dependency update

          # Return to the base directory and list files
          cd ../
          ls -la
          helm dependency update

      - name: Run chart-releaser for API Gateway
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: ./charts/canvas-api-gateway
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
  confirm-api-gateway-release:
    runs-on: ubuntu-latest
    needs: release-api-gateway
    steps:
      - name: Confirm API Gateway charts were released properly
        run: |
          # Add the required Helm repository
          helm repo add oda-canvas-api-gateway https://rj-acc.github.io/oda-canvas-api-gateway
          helm repo update

          # Check for the latest version of the apisix-gateway chart
          latest_apisix_gateway=$(helm search repo oda-canvas-api-gateway/apisix-gateway --versions | awk 'NR==2 {print $2}')
          if [ -z "$latest_apisix_gateway" ]; then
            echo "Error: apisix-gateway chart release was not successful."
            exit 1
          else
            echo "apisix-gateway chart released successfully. Version: $latest_apisix_gateway"
          fi

          # Check for the latest version of the kong-gateway chart
          latest_kong_gateway=$(helm search repo oda-canvas-api-gateway/kong-gateway --versions | awk 'NR==2 {print $2}')
          if [ -z "$latest_kong_gateway" ]; then
            echo "Error: kong-gateway chart release was not successful."
            exit 1
          else
            echo "kong-gateway chart released successfully. Version: $latest_kong_gateway"
          fi

          echo "All API Gateway charts released successfully."
