name: API Gateway and Helm Chart Release Workflow

on:
  push:
    branches:
      - 233-upgrade-gatewaysss
concurrency:
  group: chart-release
  cancel-in-progress: false

jobs:
  release-api-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Configure Helm for API Gateway
        run: |
          cd ./charts/canvas-api-gateway/combined-api-gateway-chart
          helm dependency update
          # Update dependencies for apisix-gateway chart
          cd apisix-gateway
          # Update dependencies for kong-gateway chart
          helm dependency update
          cd ../kong-gateway
          helm dependency update
          
      - name: Run chart-releaser for API Gateway Helm Charts
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: ./charts/canvas-api-gateway
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
